from django.conf import settings

RESOLVE_FORM_KEY = "AKAMARU_RESOLVE_FORM"
WORKFLOW_SESSION_KEY = "AKAMARU_WORKFLOW"
LOGIN_OK_KEY = "AKAMARU_LOGIN_OK"
LOGIN_ERROR_KEY = "AKAMARU_LOGIN_ERROR"

OPERATION_KEY = "AKAMARU_OPERATION"
OPERATION_LOGIN = "LOGIN"
OPERATION_ASSOCIATE = "ASSOCIATE"

FACEBOOK_APP_ID = getattr(settings, 'FACEBOOK_APP_ID', False)
FACEBOOK_SECRET = getattr(settings, 'FACEBOOK_SECRET', False)

VKONTAKTE_APP_ID = getattr(settings, 'VKONTAKTE_APP_ID', False)
VKONTAKTE_SECRET = getattr(settings, 'VKONTAKTE_SECRET', False)

FACEBOOK_ENABLED = 'akamaru.backends.facebook.FacebookBackend' in settings.AUTHENTICATION_BACKENDS
VKONTAKTE_ENABLED = 'akamaru.backends.vkontakte.VkontakteBackend' in settings.AUTHENTICATION_BACKENDS

assert (not FACEBOOK_ENABLED) or FACEBOOK_APP_ID
assert (not VKONTAKTE_ENABLED) or VKONTAKTE_APP_ID